//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoacaoSangueWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class doacoes_perguntas
    {
        public int id { get; set; }
        public int id_doacao { get; set; }
        public int id_pergunta { get; set; }
        public bool resposta { get; set; }
    
        public virtual doacoes doacoes { get; set; }
        public virtual perguntas perguntas { get; set; }
    }
}
