//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoacaoSangueWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class doacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doacoes()
        {
            this.doacoes_perguntas = new HashSet<doacoes_perguntas>();
        }
    
        public int id { get; set; }
        public int id_doador { get; set; }
        public Nullable<bool> aceitavel { get; set; }
        public string atendente { get; set; }
        public Nullable<double> litros { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual doadores doadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doacoes_perguntas> doacoes_perguntas { get; set; }
    }
}
